# Generated by Django 4.0.5 on 2022-07-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_message_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
    ]
