# Generated by Django 4.0.5 on 2022-07-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_room_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='Users.message'),
        ),
    ]
