# Generated by Django 4.0.5 on 2022-07-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artistas', '0001_initial'),
        ('Discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Artistas.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discos.genero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
