# Generated by Django 4.0.5 on 2022-07-13 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=75)),
                ('nombre_artistico', models.CharField(max_length=50, null=True)),
                ('banda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artistas.banda')),
            ],
            options={
                'unique_together': {('nombre', 'apellido')},
            },
        ),
    ]
