# Generated by Django 4.0.5 on 2022-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='historia',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
