# Generated by Django 4.0.5 on 2022-07-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artista_Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artistas.artista')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artistas.banda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artista',
            name='banda',
            field=models.ManyToManyField(through='Artistas.Artista_Banda', to='Artistas.banda'),
        ),
    ]
