# Generated by Django 4.0.5 on 2022-07-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0002_banda_artista_banda_artista_banda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='banda',
        ),
        migrations.AddField(
            model_name='artista',
            name='banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artistas.banda'),
        ),
        migrations.DeleteModel(
            name='Artista_Banda',
        ),
    ]
