# Generated by Django 4.0.5 on 2022-08-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0002_artista_historia_alter_artista_nombre_artistico'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='historia_banda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
