# Generated by Django 4.0.5 on 2022-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0003_banda_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Artistas'),
        ),
        migrations.AddField(
            model_name='banda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Bandas'),
        ),
    ]
