# Generated by Django 4.0.5 on 2022-07-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0003_remove_artista_banda_artista_banda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='nombre_artistico',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
