# Generated by Django 4.0.5 on 2022-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0004_artista_imagen_banda_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Artistas/'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Bandas/'),
        ),
    ]
