# Generated by Django 4.0.5 on 2022-07-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=75)),
                ('identity', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO')], max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('img', models.ImageField(blank=True, null=True, upload_to='aboutImg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
