# Generated by Django 4.0.5 on 2022-07-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.base')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=75)),
            ],
            bases=('Base.base',),
        ),
        migrations.CreateModel(
            name='PersonaMixin',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.persona')),
                ('identity', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO')], max_length=50)),
                ('tel', models.CharField(max_length=50)),
            ],
            bases=('Base.persona',),
        ),
    ]
