# Generated by Django 4.0.5 on 2022-07-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('personamixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.personamixin')),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[(1, 'ACTIVO'), (2, 'BAJA'), (3, 'MOROSO')], default='ACTIVO', max_length=50)),
            ],
            bases=('Base.personamixin',),
        ),
    ]
