# Generated by Django 4.0.5 on 2022-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=75)),
                ('identity', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[(1, 'FEMENINO'), (2, 'MASCULINO')], max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[(1, 'ACTIVO'), (2, 'BAJA'), (3, 'MOROSO')], default='ACTIVO', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
