# Generated by Django 4.0.6 on 2022-07-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disco',
            new_name='Discos',
        ),
    ]
