# Generated by Django 4.0.5 on 2022-07-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0001_initial'),
        ('Discos', '0002_rename_disco_discos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField(null=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Canciones_Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('bandas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Artistas.banda')),
                ('cancion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discos.canciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canciones',
            name='banda',
            field=models.ManyToManyField(through='Discos.Canciones_Banda', to='Artistas.banda'),
        ),
        migrations.AddField(
            model_name='canciones',
            name='discos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Discos.discos'),
        ),
    ]
