# Generated by Django 4.0.5 on 2022-07-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0003_canciones_canciones_banda_canciones_banda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canciones',
            old_name='banda',
            new_name='bandas',
        ),
        migrations.RenameField(
            model_name='canciones_banda',
            old_name='bandas',
            new_name='banda',
        ),
    ]
