# Generated by Django 4.0.5 on 2022-07-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0002_artista_historia_alter_artista_nombre_artistico'),
        ('Discos', '0004_rename_banda_canciones_bandas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Discos.genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discos',
            name='banda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Artistas.banda'),
            preserve_default=False,
        ),
    ]
