# Generated by Django 4.0.5 on 2022-07-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0005_canciones_genero_discos_banda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
