# Generated by Django 4.0.5 on 2022-08-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0006_alter_genero_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discos',
            options={'verbose_name_plural': 'Discos'},
        ),
    ]
