# Generated by Django 4.0.5 on 2022-08-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artistas', '0002_artista_historia_alter_artista_nombre_artistico'),
        ('Discos', '0007_alter_discos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canciones_Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modificated_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('artista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Artistas.artista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canciones',
            name='artistas',
            field=models.ManyToManyField(through='Discos.Canciones_Artista', to='Artistas.artista'),
        ),
        migrations.AddField(
            model_name='canciones_artista',
            name='cancion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Discos.canciones'),
        ),
    ]
